### ISSUE TITLE
Publish to Play Store

### ISSUE THREAD

**Issue by appatalks** [appatalks/Epassafe#8]
Pondering if I should publish this to the Play Store

https://play.google.com/store/apps/details?id=com.epassafe.upm

**Comment by servingbaby** [comment]
Issue:  Something about Icon Requirements

"Since July 1st 2019, all new app icons must conform to the new icon specifications. The "English (United States)" locale still does not have new icons. Upload a new app icon to adopt the new specification."

https://developer.android.com/distribute/google-play/resources/icon-design-specifications
